# Permalinks
#permalink:           pretty
root: /
permalink: /blog/:year/:month/:day/:title/

# Setup
title:               act-act
tagline:
url:                 http://masayuki038.github.io/
#paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Masayuki Takahashi
  url:               https://twitter.com/masayuki
  email:             masayuki038@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/masayuki038

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
# Gems
#gems:
#  - jekyll-paginate
#  - jekyll-gist
#whitelist:
#  - jekyll-gist
